### ISSUE TITLE
Ideia do passe de batalha

### ISSUE THREAD

**Issue by felpzo** [Manos-association-ManAss/ErreiFuiMlk-ProSoccer#11]

**Comment by artmalves** [comment]
**Passe de batalha**

O passe de batalha nada mais é do que você jogar e subir de nível do passe de batalha, com isso, receber recompensas. Há o passe de batalha pago, no qual você ao subir de nível, ganha recompensas raras e ganhará sempre que subir de nível e, no final, recebe varias ótimas recompensas de uma vez.
No passe gratuíto, no qual, ao subir alguns níveis, recebe recompensas comuns em relação ao passe de batalha pago, no final tambem haverá uma boa recompensa (em relação ao restante das recompensas do passe gratuíto).


Passe Gratuíto

Nível | Recompensa
-- | --
1 | Jogador: Kylian Mbappé
2 | Moeda In-Game (x100)
3 | Jogador: Di Maria
4 | Moeda In-Game (x150)
5 | Jogador: Iniesta
6 | Pacote de Itens
7 | Jogador: Modriĉ
8 | Moeda In-Game (x200)
9 | Jogador: Kareem Benzema (Real Madrid)
10 | Emblema de Time Personalizado
11 | Jogador: Robert Lewandowski (FC Bayern München)
12 | Moeda In-Game (x250)
13 | Jogador: Luiz Suares (MSN)
14 | Pacote de Itens
15 | Jogador: Neymar Jr. (seleção brasileira)

Passe Pago (Ícones da História + Top 15 da Última Geração)

Nível | Recompensa
-- | --
1 | Jogador: Garrincha (Versão Clássica)
2 | Pacote de Itens:
3 | Jogador: Ronaldo (Versão Clássica)
4 | Moeda In-Game (x300)
5 | Jogador: Ronaldinho Gaúcho (Versão Clássica)
6 | Pacote de Itens
7 | Jogador: Diego Maradona (Versão Clássica)
8 | Moeda In-Game (x400)
9 | Jogador: Pelé (Versão Clássica)
10 | Pacote de Itens
11 | Jogador: Cristiano Ronaldo (Versão do Real Madrid)
12 | Moeda In-Game (x500)
13 | Jogador: Lionel Messi(Versão do Barcelona)
14 | Pacote de Itens: Celebrações de Luxo
15 | Jogadores: Pelé
